### ISSUE TITLE
Error on compilation

### ISSUE THREAD

**Issue by 1Mack** [xyligan-gp/CheckCheats#1]
CheckCheats_teste.sp(790) : error 100: function prototypes do not match
CheckCheats_teste.sp(794) : error 100: function prototypes do not match

**Comment by xyligan-gp** [comment]
Какая версия SM?

**Comment by shadowplay1** [comment]
это не русский чел, если что)

**Comment by 1Mack** [comment]
The problem was the version of SM

**Comment by shadowplay1** [comment]
glad you solved ur issue :)
